import type { Meta, StoryObj } from '@storybook/react-vite';
import { fn } from '@storybook/test';

import EventFormPanel from './EventFormPanel';

// Mock handlers
const meta: Meta<typeof EventFormPanel> = {
  title: 'Components/EventFormPanel',
  component: EventFormPanel,
  parameters: {
    layout: 'padded',
  },
  tags: ['autodocs'],
  args: {
    onSubmit: fn(),
  },
};

export default meta;
type Story = StoryObj<typeof meta>;

// 일정 추가 모드
export const AddMode: Story = {
  args: {
    editingEvent: null,
    title: '',
    setTitle: fn(),
    date: '2024-11-15',
    setDate: fn(),
    startTime: '09:00',
    endTime: '10:00',
    handleStartTimeChange: fn(),
    handleEndTimeChange: fn(),
    startTimeError: null,
    endTimeError: null,
    description: '',
    setDescription: fn(),
    location: '',
    setLocation: fn(),
    category: '업무',
    setCategory: fn(),
    isRepeating: false,
    setIsRepeating: fn(),
    repeatType: 'none',
    setRepeatType: fn(),
    repeatInterval: 1,
    setRepeatInterval: fn(),
    repeatEndDate: '',
    setRepeatEndDate: fn(),
    notificationTime: 10,
    setNotificationTime: fn(),
  },
};

// 일정 추가 모드 (필드 채워진 상태)
export const AddModeWithData: Story = {
  args: {
    editingEvent: null,
    title: '팀 미팅 (시각적 회귀 테스트)',
    setTitle: fn(),
    date: '2024-11-15',
    setDate: fn(),
    startTime: '14:00',
    endTime: '15:30',
    handleStartTimeChange: fn(),
    handleEndTimeChange: fn(),
    startTimeError: null,
    endTimeError: null,
    description: '주간 업무 회의',
    setDescription: fn(),
    location: '회의실 A',
    setLocation: fn(),
    category: '업무',
    setCategory: fn(),
    isRepeating: false,
    setIsRepeating: fn(),
    repeatType: 'none',
    setRepeatType: fn(),
    repeatInterval: 1,
    setRepeatInterval: fn(),
    repeatEndDate: '',
    setRepeatEndDate: fn(),
    notificationTime: 10,
    setNotificationTime: fn(),
  },
};

// 반복 일정 추가 모드
export const RepeatingEvent: Story = {
  args: {
    editingEvent: null,
    title: '매일 운동',
    setTitle: fn(),
    date: '2024-11-15',
    setDate: fn(),
    startTime: '07:00',
    endTime: '08:00',
    handleStartTimeChange: fn(),
    handleEndTimeChange: fn(),
    startTimeError: null,
    endTimeError: null,
    description: '아침 조깅',
    setDescription: fn(),
    location: '공원',
    setLocation: fn(),
    category: '개인',
    setCategory: fn(),
    isRepeating: true,
    setIsRepeating: fn(),
    repeatType: 'daily',
    setRepeatType: fn(),
    repeatInterval: 1,
    setRepeatInterval: fn(),
    repeatEndDate: '2024-12-31',
    setRepeatEndDate: fn(),
    notificationTime: 60,
    setNotificationTime: fn(),
  },
};

// 일정 수정 모드
export const EditMode: Story = {
  args: {
    editingEvent: {
      id: '1',
      title: '기존 미팅',
      date: '2024-11-15',
      startTime: '10:00',
      endTime: '11:00',
      description: '수정할 미팅',
      location: '회의실 B',
      category: '업무',
      repeat: {
        type: 'none',
        interval: 0,
      },
      notificationTime: 10,
    },
    title: '기존 미팅',
    setTitle: fn(),
    date: '2024-11-15',
    setDate: fn(),
    startTime: '10:00',
    endTime: '11:00',
    handleStartTimeChange: fn(),
    handleEndTimeChange: fn(),
    startTimeError: null,
    endTimeError: null,
    description: '수정할 미팅',
    setDescription: fn(),
    location: '회의실 B',
    setLocation: fn(),
    category: '업무',
    setCategory: fn(),
    isRepeating: false,
    setIsRepeating: fn(),
    repeatType: 'none',
    setRepeatType: fn(),
    repeatInterval: 1,
    setRepeatInterval: fn(),
    repeatEndDate: '',
    setRepeatEndDate: fn(),
    notificationTime: 10,
    setNotificationTime: fn(),
  },
};

// 시간 에러 상태
export const WithTimeError: Story = {
  args: {
    editingEvent: null,
    title: '잘못된 시간',
    setTitle: fn(),
    date: '2024-11-15',
    setDate: fn(),
    startTime: '10:00',
    endTime: '09:00',
    handleStartTimeChange: fn(),
    handleEndTimeChange: fn(),
    startTimeError: '시작 시간은 종료 시간보다 빨라야 합니다.',
    endTimeError: '종료 시간은 시작 시간보다 늦어야 합니다.',
    description: '',
    setDescription: fn(),
    location: '',
    setLocation: fn(),
    category: '업무',
    setCategory: fn(),
    isRepeating: false,
    setIsRepeating: fn(),
    repeatType: 'none',
    setRepeatType: fn(),
    repeatInterval: 1,
    setRepeatInterval: fn(),
    repeatEndDate: '',
    setRepeatEndDate: fn(),
    notificationTime: 10,
    setNotificationTime: fn(),
  },
};

// ===== 4. 폼 컨트롤 상태 시각적 회귀 테스트 =====

// 모든 필드 채워진 상태
export const AllFieldsFilled: Story = {
  args: {
    editingEvent: null,
    title: '완전한 일정',
    setTitle: fn(),
    date: '2024-11-15',
    setDate: fn(),
    startTime: '14:00',
    endTime: '15:30',
    handleStartTimeChange: fn(),
    handleEndTimeChange: fn(),
    startTimeError: null,
    endTimeError: null,
    description: '매우 상세한 설명이 포함된 일정입니다. 이 일정은 모든 필드가 채워져 있어서 폼의 완성된 상태를 보여줍니다.',
    setDescription: fn(),
    location: '서울특별시 강남구 테헤란로 123, 빌딩 4층 회의실 A',
    setLocation: fn(),
    category: '업무',
    setCategory: fn(),
    isRepeating: true,
    setIsRepeating: fn(),
    repeatType: 'weekly',
    setRepeatType: fn(),
    repeatInterval: 2,
    setRepeatInterval: fn(),
    repeatEndDate: '2024-12-31',
    setRepeatEndDate: fn(),
    notificationTime: 10,
    setNotificationTime: fn(),
  },
};

// 긴 텍스트 입력
export const LongTextInputs: Story = {
  args: {
    editingEvent: null,
    title: '매우 긴 제목을 가진 일정입니다. 제목이 너무 길면 UI에서 어떻게 처리되는지 테스트합니다. 이것은 시각적 회귀 테스트를 위한 예시입니다.',
    setTitle: fn(),
    date: '2024-11-15',
    setDate: fn(),
    startTime: '14:00',
    endTime: '15:30',
    handleStartTimeChange: fn(),
    handleEndTimeChange: fn(),
    startTimeError: null,
    endTimeError: null,
    description: '매우 긴 설명입니다. '.repeat(50),
    setDescription: fn(),
    location: '매우 긴 위치 정보입니다. 서울특별시 강남구 테헤란로 123번길 45, 건물명은 매우 긴 이름을 가진 빌딩, 4층 회의실 A호',
    setLocation: fn(),
    category: '업무',
    setCategory: fn(),
    isRepeating: false,
    setIsRepeating: fn(),
    repeatType: 'none',
    setRepeatType: fn(),
    repeatInterval: 1,
    setRepeatInterval: fn(),
    repeatEndDate: '',
    setRepeatEndDate: fn(),
    notificationTime: 10,
    setNotificationTime: fn(),
  },
};

// 반복 일정 - 간격 설정
export const RepeatingWithInterval: Story = {
  args: {
    editingEvent: null,
    title: '2주마다 반복',
    setTitle: fn(),
    date: '2024-11-15',
    setDate: fn(),
    startTime: '10:00',
    endTime: '11:00',
    handleStartTimeChange: fn(),
    handleEndTimeChange: fn(),
    startTimeError: null,
    endTimeError: null,
    description: '격주 회의',
    setDescription: fn(),
    location: '회의실',
    setLocation: fn(),
    category: '업무',
    setCategory: fn(),
    isRepeating: true,
    setIsRepeating: fn(),
    repeatType: 'weekly',
    setRepeatType: fn(),
    repeatInterval: 2,
    setRepeatInterval: fn(),
    repeatEndDate: '2024-12-31',
    setRepeatEndDate: fn(),
    notificationTime: 10,
    setNotificationTime: fn(),
  },
};

// 다양한 카테고리
export const CategoryFamily: Story = {
  args: {
    editingEvent: null,
    title: '가족 모임',
    setTitle: fn(),
    date: '2024-11-15',
    setDate: fn(),
    startTime: '18:00',
    endTime: '21:00',
    handleStartTimeChange: fn(),
    handleEndTimeChange: fn(),
    startTimeError: null,
    endTimeError: null,
    description: '저녁 식사',
    setDescription: fn(),
    location: '집',
    setLocation: fn(),
    category: '가족',
    setCategory: fn(),
    isRepeating: false,
    setIsRepeating: fn(),
    repeatType: 'none',
    setRepeatType: fn(),
    repeatInterval: 1,
    setRepeatInterval: fn(),
    repeatEndDate: '',
    setRepeatEndDate: fn(),
    notificationTime: 60,
    setNotificationTime: fn(),
  },
};

export const CategoryOther: Story = {
  args: {
    editingEvent: null,
    title: '기타 일정',
    setTitle: fn(),
    date: '2024-11-15',
    setDate: fn(),
    startTime: '10:00',
    endTime: '11:00',
    handleStartTimeChange: fn(),
    handleEndTimeChange: fn(),
    startTimeError: null,
    endTimeError: null,
    description: '기타',
    setDescription: fn(),
    location: '어딘가',
    setLocation: fn(),
    category: '기타',
    setCategory: fn(),
    isRepeating: false,
    setIsRepeating: fn(),
    repeatType: 'none',
    setRepeatType: fn(),
    repeatInterval: 1,
    setRepeatInterval: fn(),
    repeatEndDate: '',
    setRepeatEndDate: fn(),
    notificationTime: 10,
    setNotificationTime: fn(),
  },
};

// 다양한 알림 시간
export const NotificationOneMinute: Story = {
  args: {
    editingEvent: null,
    title: '긴급 미팅',
    setTitle: fn(),
    date: '2024-11-15',
    setDate: fn(),
    startTime: '09:00',
    endTime: '10:00',
    handleStartTimeChange: fn(),
    handleEndTimeChange: fn(),
    startTimeError: null,
    endTimeError: null,
    description: '1분 전 알림',
    setDescription: fn(),
    location: '회의실',
    setLocation: fn(),
    category: '업무',
    setCategory: fn(),
    isRepeating: false,
    setIsRepeating: fn(),
    repeatType: 'none',
    setRepeatType: fn(),
    repeatInterval: 1,
    setRepeatInterval: fn(),
    repeatEndDate: '',
    setRepeatEndDate: fn(),
    notificationTime: 1,
    setNotificationTime: fn(),
  },
};

export const NotificationOneDay: Story = {
  args: {
    editingEvent: null,
    title: '중요 이벤트',
    setTitle: fn(),
    date: '2024-11-20',
    setDate: fn(),
    startTime: '14:00',
    endTime: '16:00',
    handleStartTimeChange: fn(),
    handleEndTimeChange: fn(),
    startTimeError: null,
    endTimeError: null,
    description: '하루 전 알림',
    setDescription: fn(),
    location: '본사',
    setLocation: fn(),
    category: '업무',
    setCategory: fn(),
    isRepeating: false,
    setIsRepeating: fn(),
    repeatType: 'none',
    setRepeatType: fn(),
    repeatInterval: 1,
    setRepeatInterval: fn(),
    repeatEndDate: '',
    setRepeatEndDate: fn(),
    notificationTime: 1440,
    setNotificationTime: fn(),
  },
};
